name: SILShack Summer 2018

title: SILShack

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM

future: true

timezone: America/New_York

# You betcha
gems:
  - jemoji

# Categories to exclude from the index
special-categories:
  - "exercise"
  - "how-to"
  - "sidebar"
  - "reading"
  - "notes"

# Exclude Jekyll's built-in tests
exclude: [vendor]

# These can contain uppercase: they'll be lowercased in the URL
page-order:
  - syllabus
  - assignments
  - how-to
  - people

# Same note RE case above
python-extra-pages:
  - console


permalink: none

baseurl: /summer2018
url: /summer2018

python: true

course:
  title: Programming for Information Professionals
  number: INLS 560
  instructor: Prof. Elliott Hauser
  semester: Summer 2018

authors:
  elliott:
    name: Elliott Hauser
    prof: true
    gravatar: 0d0d432948d262195358f339768f1240
    website: http://www.elliotthauser.com
    github: eah13
    twitter: hauspoor
    about:  Elliott Hauser is a PhD Student in information science at UNC Chapel Hill.  He's hacking education as one of the cofounders of Trinket.io.

  tommytester:
    name: Tommy Tester
    prof: false
    gravatar:
    website: "#"
    github: tommytester
    twitter:
    about: "Testin' INLS 560 since 2014"

  draravindrk:
    name: draravindrk
    prof: false
    gravatar:
    website: "https://developers.google.com/edu/python/"
    github: draravindrk
    twitter: "arvireddymd"
    about: "Here's a little about draravindrk"

  hollaATyacodegirl:
    name: Halina Krzystek
    prof: false
    gravatar: "edea51a5dc5f2e831a89d677ff72140c"
    website: "#"
    github: hollaATyacodegirl
    twitter: "https://twitter.com/HaleezyK"
    about: "Halina is a grad student at UNC Chapel Hill in North Carolina, pursuing a PSM in Biomedical Informatics. She is interested in 
    the analysis of large biological data sets to inform health decisions."

  kevin-kao:
    name: kevin-kao
    prof: false
    gravatar:
    website: https://www.linkedin.com/in/sheng-kai-kevin-kao-dukefuqua/
    github: kevin-kao
    twitter:
    about: "I am a visiting student here in UNC and an incoming student at Duke University studying quantitative management for my master degree this fall."

  NobrineCalc:
    name: Damola Ajao
    prof: false
    gravatar:
    website: "#"
    github: NobrineCalc
    twitter:
    about: "Here's a little about Damola"

  ponderm:
    name: ponderm
    prof: false
    gravatar:
    website: "#"
    github: ponderm
    twitter:
    about: "Here's a little about ponderm"

  rachelanniexo:
    name: Rachel Anne 
    prof: false
    gravatar: af6099f46ccc4e71fe04e26cca7a787a
    website: "#"
    github: rachelanniexo
    twitter: rachelanniexo
    about: "Rachel Anne is a rising second-year MSIS student interested in UX."

  scylarmartin:
    name: scylarmartin
    prof: false
    gravatar:
    website: "#"
    github: scylarmartin
    twitter:
    about: "Here's a little about scylarmartin"

  TCarmon:
    name: Tia Carmon
    prof: false
    gravatar: "05ff2bf3c30c499fffb44135c332a01c"
    website: "https://www.linkedin.com/in/tiacarmon/"
    github: TCarmon
    twitter: "tiacarmon"
    about: "Tia is a BMHI student spending Summer 2018 taking INLS 560"

  WildGinger23:
    name: WildGinger23
    prof: false
    gravatar:
    website: "#"
    github: WildGinger23
    twitter:
    about: "Here's a little about WildGinger23"




baseurl:
url:


baseurl:
url:

